name: 🚀 Feature Request
description: Suggest an idea for the DDO Database project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Quest Database Enhancement
        - Optimization Algorithm
        - User Interface Improvement  
        - API Enhancement
        - Performance Improvement
        - Documentation
        - Testing
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for workflow
        - Critical - Blocking current usage
    validations:
      required: true
      
  - type: checkboxes
    id: ddo-context
    attributes:
      label: DDO Context
      description: Which DDO aspects does this feature relate to?
      options:
        - label: Quest optimization and leveling paths
        - label: Character progression tracking
        - label: Saga completion and rewards
        - label: Adventure pack organization
        - label: XP calculation and efficiency
        - label: Community features and sharing
        - label: Data accuracy and wiki integration
        - label: Mobile/responsive experience
        
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or DDO-specific details about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
